export type RiskLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export type CountryRecord = {
  name: string;
  capital: string;
  population: string;
  region: string;
  riskLevel: RiskLevel;
  stabilityScore: number;
  leader: { name: string; title: string };
  summary: string;
  currentSituation: string;
  timeline: { year: string; event: string }[];
  conflicts: { name: string; status: "active" | "frozen" | "resolved"; since: string }[];
  allies: string[];
  rivals: string[];
};

export const DOOMSDAY_BASE_SECONDS = 90;

export const COUNTRY_DATABASE: Record<string, CountryRecord> = {
  "United States": {
    name: "United States",
    capital: "Washington, D.C.",
    population: "331 million",
    region: "North America",
    riskLevel: 3,
    stabilityScore: 72,
    leader: { name: "Joe Biden", title: "President" },
    summary: "The world's leading military and economic superpower, currently navigating domestic polarization and managing multiple global security commitments.",
    currentSituation: "Leading NATO support for Ukraine; managing tensions with China over Taiwan; domestic political division remains high.",
    timeline: [
      { year: "1945", event: "Emerges as global superpower after WWII; cofounds the United Nations" },
      { year: "1969", event: "Apollo 11 — first humans land on the Moon" },
      { year: "1991", event: "Cold War ends; Soviet Union dissolves" },
      { year: "2001", event: "9/11 attacks launch the Global War on Terror" },
      { year: "2008", event: "Global financial crisis; first African-American president elected" },
      { year: "2020", event: "COVID-19 pandemic; nationwide social justice protests" },
      { year: "2022", event: "Leads Western military aid to Ukraine against Russian invasion" },
    ],
    conflicts: [
      { name: "Global Counterterrorism", status: "active", since: "2001" },
      { name: "Cold War with China", status: "active", since: "2018" },
    ],
    allies: ["United Kingdom", "Canada", "France", "Germany", "Japan", "Australia", "South Korea"],
    rivals: ["Russia", "China", "North Korea", "Iran"],
  },
  "Russia": {
    name: "Russia",
    capital: "Moscow",
    population: "144 million",
    region: "Eastern Europe / North Asia",
    riskLevel: 9,
    stabilityScore: 32,
    leader: { name: "Vladimir Putin", title: "President" },
    summary: "Russia is engaged in a full-scale war in Ukraine and is under sweeping Western sanctions. It seeks a multipolar world order counter to US-led institutions.",
    currentSituation: "Ongoing war in Ukraine; deepening partnership with China; economy under severe sanctions.",
    timeline: [
      { year: "1917", event: "Bolshevik Revolution establishes the Soviet state" },
      { year: "1991", event: "Soviet Union dissolves; Russian Federation established" },
      { year: "2000", event: "Putin comes to power; begins recentralizing authority" },
      { year: "2008", event: "War with Georgia; recognition of breakaway regions" },
      { year: "2014", event: "Annexes Crimea; backs separatists in Donbas" },
      { year: "2022", event: "Launches full-scale invasion of Ukraine" },
      { year: "2023", event: "Wagner Group mutiny; ongoing grinding war" },
    ],
    conflicts: [
      { name: "Russo-Ukrainian War", status: "active", since: "2022" },
      { name: "Syria Intervention", status: "active", since: "2015" },
    ],
    allies: ["Belarus", "China", "Iran", "North Korea", "Syria"],
    rivals: ["United States", "Ukraine", "NATO members"],
  },
  "China": {
    name: "China",
    capital: "Beijing",
    population: "1.4 billion",
    region: "East Asia",
    riskLevel: 7,
    stabilityScore: 55,
    leader: { name: "Xi Jinping", title: "President / General Secretary" },
    summary: "China is the world's second-largest economy and rising military power. Taiwan remains the primary flashpoint while the Belt and Road Initiative extends global influence.",
    currentSituation: "Escalating military drills near Taiwan; strategic competition with US; economic slowdown concerns.",
    timeline: [
      { year: "1949", event: "People's Republic of China founded after civil war" },
      { year: "1978", event: "Deng Xiaoping launches economic reform era" },
      { year: "1989", event: "Tiananmen Square crackdown" },
      { year: "2001", event: "Joins World Trade Organization; economic boom accelerates" },
      { year: "2013", event: "Xi Jinping consolidates power; Belt and Road Initiative launched" },
      { year: "2020", event: "COVID-19 pandemic originates in Wuhan; Hong Kong security law imposed" },
      { year: "2023", event: "Brokers Saudi-Iran normalization; Taiwan tensions intensify" },
    ],
    conflicts: [
      { name: "Taiwan Strait Tensions", status: "active", since: "1949" },
      { name: "South China Sea Disputes", status: "active", since: "2009" },
      { name: "India Border Standoff", status: "frozen", since: "1962" },
    ],
    allies: ["Russia", "Pakistan", "North Korea", "Cambodia"],
    rivals: ["United States", "Taiwan", "Japan", "India"],
  },
  "Ukraine": {
    name: "Ukraine",
    capital: "Kyiv",
    population: "44 million",
    region: "Eastern Europe",
    riskLevel: 10,
    stabilityScore: 18,
    leader: { name: "Volodymyr Zelensky", title: "President" },
    summary: "Ukraine is fighting a full-scale war for survival against Russian invasion, sustained by unprecedented Western military and financial support.",
    currentSituation: "Active war on multiple fronts; significant territorial losses in east; massive civilian displacement.",
    timeline: [
      { year: "1991", event: "Independence from Soviet Union declared" },
      { year: "2004", event: "Orange Revolution brings pro-Western government" },
      { year: "2014", event: "Maidan Revolution; Russia annexes Crimea; Donbas war begins" },
      { year: "2019", event: "Zelensky elected president in landslide" },
      { year: "2022", event: "Russia launches full-scale invasion on February 24" },
      { year: "2023", event: "Ukrainian counteroffensive; Wagner mutiny aids Ukrainian morale" },
    ],
    conflicts: [
      { name: "Russo-Ukrainian War", status: "active", since: "2022" },
      { name: "Donbas Conflict", status: "active", since: "2014" },
    ],
    allies: ["United States", "United Kingdom", "Poland", "Germany", "EU"],
    rivals: ["Russia", "Belarus"],
  },
  "India": {
    name: "India",
    capital: "New Delhi",
    population: "1.43 billion",
    region: "South Asia",
    riskLevel: 4,
    stabilityScore: 62,
    leader: { name: "Narendra Modi", title: "Prime Minister" },
    summary: "World's most populous democracy and fastest-growing major economy. Maintains strategic autonomy, balancing ties with the US, Russia, and China.",
    currentSituation: "G20 leadership; border tensions with China ongoing; Kashmir dispute with Pakistan continues.",
    timeline: [
      { year: "1947", event: "Independence from Britain; partition creates Pakistan" },
      { year: "1962", event: "Border war with China" },
      { year: "1974", event: "First nuclear weapons test ('Smiling Buddha')" },
      { year: "1991", event: "Economic liberalization transforms the economy" },
      { year: "1998", event: "Second nuclear tests; declared nuclear weapons state" },
      { year: "2014", event: "Modi elected; Hindu nationalist politics rise" },
      { year: "2023", event: "Becomes world's most populous nation; G20 presidency" },
    ],
    conflicts: [
      { name: "Kashmir Dispute", status: "active", since: "1947" },
      { name: "China Border Tensions", status: "frozen", since: "1962" },
    ],
    allies: ["United States", "France", "Israel", "Australia"],
    rivals: ["Pakistan", "China"],
  },
  "Pakistan": {
    name: "Pakistan",
    capital: "Islamabad",
    population: "220 million",
    region: "South Asia",
    riskLevel: 8,
    stabilityScore: 28,
    leader: { name: "Shehbaz Sharif", title: "Prime Minister" },
    summary: "Nuclear-armed state facing severe economic crisis, political instability, and ongoing terrorism threats from Afghan border regions.",
    currentSituation: "Economic crisis with IMF bailout; political turmoil following Imran Khan's arrest; Taliban spillover from Afghanistan.",
    timeline: [
      { year: "1947", event: "Created as Muslim homeland at partition from British India" },
      { year: "1971", event: "East Pakistan breaks away to form Bangladesh" },
      { year: "1998", event: "Nuclear tests in response to India; sanctions imposed" },
      { year: "2001", event: "Key US ally in War on Terror; Taliban cross-border operations" },
      { year: "2022", event: "PM Imran Khan removed via no-confidence vote" },
      { year: "2023", event: "Imran Khan arrested; severe economic instability" },
    ],
    conflicts: [
      { name: "Kashmir Dispute", status: "active", since: "1947" },
      { name: "TTP Insurgency", status: "active", since: "2007" },
    ],
    allies: ["China", "Saudi Arabia", "Turkey"],
    rivals: ["India", "Afghanistan"],
  },
  "North Korea": {
    name: "North Korea",
    capital: "Pyongyang",
    population: "26 million",
    region: "East Asia",
    riskLevel: 9,
    stabilityScore: 12,
    leader: { name: "Kim Jong-un", title: "Supreme Leader" },
    summary: "Highly secretive totalitarian state with active nuclear and ballistic missile programs. Increasingly partnering with Russia for military cooperation.",
    currentSituation: "Multiple ICBM tests; providing artillery shells to Russia; satellite launch attempts; extreme food insecurity.",
    timeline: [
      { year: "1948", event: "Democratic People's Republic of Korea founded" },
      { year: "1950", event: "Korean War begins; armistice signed in 1953" },
      { year: "1994", event: "Kim Il-sung dies; Kim Jong-il takes power" },
      { year: "2006", event: "First nuclear weapons test conducted" },
      { year: "2011", event: "Kim Jong-un comes to power after father's death" },
      { year: "2017", event: "Multiple ICBM tests; hydrogen bomb test" },
      { year: "2023", event: "Supplies ammunition to Russia; escalates missile program" },
    ],
    conflicts: [
      { name: "Korean Peninsula Tension", status: "frozen", since: "1953" },
      { name: "Nuclear Standoff", status: "active", since: "2006" },
    ],
    allies: ["Russia", "China"],
    rivals: ["South Korea", "United States", "Japan"],
  },
  "Iran": {
    name: "Iran",
    capital: "Tehran",
    population: "86 million",
    region: "Middle East",
    riskLevel: 8,
    stabilityScore: 30,
    leader: { name: "Ebrahim Raisi", title: "President" },
    summary: "Iran is a major regional power with a nuclear program nearing weapons-grade enrichment. It leads the 'Axis of Resistance' backing Hamas, Hezbollah, and Houthi forces.",
    currentSituation: "Nuclear talks stalled; backing Hamas and Hezbollah; Houthi attacks on Red Sea shipping; drone war with Israel.",
    timeline: [
      { year: "1979", event: "Islamic Revolution; US embassy hostage crisis" },
      { year: "1980", event: "Iraq-Iran War begins; lasts 8 years" },
      { year: "2002", event: "Nuclear program revealed; international sanctions begin" },
      { year: "2015", event: "JCPOA nuclear deal signed with world powers" },
      { year: "2018", event: "US withdraws from nuclear deal; sanctions reimposed" },
      { year: "2023", event: "Record uranium enrichment; brokered Saudi-Iran normalization with China" },
    ],
    conflicts: [
      { name: "Nuclear Standoff", status: "active", since: "2002" },
      { name: "Yemen Proxy War", status: "active", since: "2015" },
      { name: "Israel Shadow War", status: "active", since: "2021" },
    ],
    allies: ["Russia", "China", "Syria", "Hezbollah", "Hamas"],
    rivals: ["United States", "Israel", "Saudi Arabia"],
  },
  "Israel": {
    name: "Israel",
    capital: "Jerusalem",
    population: "9.3 million",
    region: "Middle East",
    riskLevel: 9,
    stabilityScore: 38,
    leader: { name: "Benjamin Netanyahu", title: "Prime Minister" },
    summary: "Engaged in multi-front conflict following Hamas's October 7 attack. Faces war in Gaza, Hezbollah skirmishes, and drone exchanges with Iran.",
    currentSituation: "Major military operation in Gaza; Hezbollah exchanges on northern border; first direct Iran drone attack repelled.",
    timeline: [
      { year: "1948", event: "State of Israel declared; Arab-Israeli War follows" },
      { year: "1967", event: "Six-Day War; Israel occupies West Bank, Gaza, Sinai" },
      { year: "1979", event: "Peace treaty with Egypt" },
      { year: "1993", event: "Oslo Accords with PLO; Palestinian Authority created" },
      { year: "2005", event: "Disengages from Gaza; Hamas wins 2006 elections" },
      { year: "2023", event: "Hamas October 7 attacks; major Gaza military operation begins" },
    ],
    conflicts: [
      { name: "Gaza War", status: "active", since: "2023" },
      { name: "Lebanon Border Clashes", status: "active", since: "2023" },
      { name: "Palestinian Conflict", status: "active", since: "1948" },
    ],
    allies: ["United States", "Germany", "UK", "UAE", "Bahrain"],
    rivals: ["Iran", "Hamas", "Hezbollah", "Syria"],
  },
  "Saudi Arabia": {
    name: "Saudi Arabia",
    capital: "Riyadh",
    population: "35 million",
    region: "Middle East",
    riskLevel: 5,
    stabilityScore: 52,
    leader: { name: "Mohammed bin Salman", title: "Crown Prince / PM" },
    summary: "Dominant Gulf power undergoing economic transformation under Vision 2030. Normalizing ties with Iran and pursuing unprecedented diplomatic balancing act.",
    currentSituation: "Yemen war winding down; Saudi-Iran normalization progressing; Israel normalization talks paused post-Oct 7.",
    timeline: [
      { year: "1932", event: "Kingdom of Saudi Arabia officially unified" },
      { year: "1973", event: "Oil embargo shocks the global economy" },
      { year: "1990", event: "Hosts US troops for Gulf War; jihadist backlash grows" },
      { year: "2015", event: "Begins Yemen war against Houthi forces; King Salman ascends" },
      { year: "2017", event: "MBS consolidates power; Vision 2030 launched" },
      { year: "2023", event: "Saudi-Iran normalization brokered by China" },
    ],
    conflicts: [
      { name: "Yemen Intervention", status: "active", since: "2015" },
    ],
    allies: ["United States", "UAE", "Egypt", "Jordan"],
    rivals: ["Iran", "Qatar (historically)"],
  },
  "Germany": {
    name: "Germany",
    capital: "Berlin",
    population: "83 million",
    region: "Western Europe",
    riskLevel: 2,
    stabilityScore: 78,
    leader: { name: "Olaf Scholz", title: "Chancellor" },
    summary: "Europe's largest economy and pivotal NATO member. Undertaking historic 'Zeitenwende' military buildup following Russia's Ukraine invasion.",
    currentSituation: "Major military aid to Ukraine; ending Russian gas dependency; internal coalition tensions.",
    timeline: [
      { year: "1945", event: "WWII ends; Germany divided into East and West" },
      { year: "1949", event: "West Germany joins NATO; East Germany formed" },
      { year: "1989", event: "Berlin Wall falls" },
      { year: "1990", event: "Reunification of Germany" },
      { year: "2005", event: "Angela Merkel becomes first female chancellor" },
      { year: "2022", event: "Announces 'Zeitenwende' (turning point) defense policy; major Ukraine aid" },
    ],
    conflicts: [],
    allies: ["United States", "France", "Poland", "EU", "NATO"],
    rivals: ["Russia"],
  },
  "France": {
    name: "France",
    capital: "Paris",
    population: "68 million",
    region: "Western Europe",
    riskLevel: 2,
    stabilityScore: 74,
    leader: { name: "Emmanuel Macron", title: "President" },
    summary: "Permanent UN Security Council member and nuclear power. Pushing for European strategic autonomy while managing domestic political challenges.",
    currentSituation: "Political tensions; withdrawing from West Africa amid coups; strong Ukraine support.",
    timeline: [
      { year: "1789", event: "French Revolution reshapes political thought globally" },
      { year: "1945", event: "Liberation from Nazi occupation; joins UN Security Council" },
      { year: "1958", event: "Fifth Republic established by De Gaulle" },
      { year: "1968", event: "Student revolts and general strikes" },
      { year: "2015", event: "Paris terrorist attacks; leads Sahel intervention" },
      { year: "2022", event: "Macron re-elected; escalating Ukraine support" },
    ],
    conflicts: [
      { name: "Sahel Insurgency", status: "resolved", since: "2013" },
    ],
    allies: ["United States", "Germany", "UK", "EU", "NATO"],
    rivals: ["Russia"],
  },
  "United Kingdom": {
    name: "United Kingdom",
    capital: "London",
    population: "67 million",
    region: "Western Europe",
    riskLevel: 2,
    stabilityScore: 73,
    leader: { name: "Rishi Sunak", title: "Prime Minister" },
    summary: "Major NATO power navigating post-Brexit identity while remaining a key security partner for both the US and Europe.",
    currentSituation: "Strong Ukraine support; AUKUS security pact with US and Australia; Northern Ireland protocol issues.",
    timeline: [
      { year: "1945", event: "Wins WWII; begins empire decolonization" },
      { year: "1973", event: "Joins European Economic Community" },
      { year: "1997", event: "Hong Kong returned to China" },
      { year: "2016", event: "Brexit referendum; votes to leave EU" },
      { year: "2020", event: "Officially leaves the European Union" },
      { year: "2022", event: "Queen Elizabeth II dies after 70-year reign" },
    ],
    conflicts: [],
    allies: ["United States", "France", "Australia", "Canada", "NATO"],
    rivals: ["Russia"],
  },
  "Japan": {
    name: "Japan",
    capital: "Tokyo",
    population: "125 million",
    region: "East Asia",
    riskLevel: 3,
    stabilityScore: 77,
    leader: { name: "Fumio Kishida", title: "Prime Minister" },
    summary: "World's third-largest economy undergoing historic military buildup to counter North Korean and Chinese threats while strengthening US alliance.",
    currentSituation: "Historic defense budget increase; strengthening US-Japan alliance; North Korean missile overflights.",
    timeline: [
      { year: "1945", event: "Atomic bombing of Hiroshima and Nagasaki; WWII ends" },
      { year: "1964", event: "Tokyo Olympics; postwar economic miracle in full swing" },
      { year: "1989", event: "Emperor Hirohito dies; Heisei era begins" },
      { year: "2011", event: "Tōhoku earthquake, tsunami, Fukushima nuclear disaster" },
      { year: "2023", event: "G7 host; historic defense spending increase" },
    ],
    conflicts: [
      { name: "Territorial Disputes with China", status: "frozen", since: "1970s" },
    ],
    allies: ["United States", "South Korea", "Australia"],
    rivals: ["China", "North Korea", "Russia"],
  },
  "South Korea": {
    name: "South Korea",
    capital: "Seoul",
    population: "52 million",
    region: "East Asia",
    riskLevel: 5,
    stabilityScore: 68,
    leader: { name: "Yoon Suk-yeol", title: "President" },
    summary: "Major tech and manufacturing power on the frontline with North Korea. Strengthening US alliance while navigating complex China relationship.",
    currentSituation: "North Korean provocations escalating; trilateral US-Japan-Korea partnership strengthening.",
    timeline: [
      { year: "1950", event: "Korean War begins" },
      { year: "1953", event: "Armistice signed; Korean peninsula divided" },
      { year: "1988", event: "Seoul Olympics; democratization complete" },
      { year: "1997", event: "Asian financial crisis; IMF bailout" },
      { year: "2023", event: "Camp David summit with US and Japan; North Korea escalations" },
    ],
    conflicts: [
      { name: "Korean Peninsula Tension", status: "frozen", since: "1953" },
    ],
    allies: ["United States", "Japan", "Australia"],
    rivals: ["North Korea", "China"],
  },
  "Brazil": {
    name: "Brazil",
    capital: "Brasília",
    population: "215 million",
    region: "South America",
    riskLevel: 4,
    stabilityScore: 55,
    leader: { name: "Luiz Inácio Lula da Silva", title: "President" },
    summary: "South America's largest nation and economy. Lula's return marks a shift back to progressive politics and re-engagement with multilateral climate frameworks.",
    currentSituation: "Amazon deforestation declining under Lula; hosting COP30; economic stabilization.",
    timeline: [
      { year: "1500", event: "Portuguese arrival; colonization begins" },
      { year: "1889", event: "Republic declared" },
      { year: "1964", event: "Military coup; 21 years of dictatorship" },
      { year: "1985", event: "Return to democracy" },
      { year: "2002", event: "Lula elected president; social programs launched" },
      { year: "2022", event: "Lula defeats Bolsonaro; January 8 Capitol-style attack" },
    ],
    conflicts: [],
    allies: ["Argentina", "Chile", "EU", "African Union"],
    rivals: [],
  },
  "Mexico": {
    name: "Mexico",
    capital: "Mexico City",
    population: "128 million",
    region: "North America",
    riskLevel: 6,
    stabilityScore: 44,
    leader: { name: "Andrés Manuel López Obrador", title: "President" },
    summary: "North America's second-largest economy grappling with cartel violence that has turned several states into conflict zones.",
    currentSituation: "Cartel wars claim 30,000+ lives annually; record fentanyl production; US relations strained.",
    timeline: [
      { year: "1910", event: "Mexican Revolution begins" },
      { year: "1994", event: "NAFTA takes effect; Zapatista uprising in Chiapas" },
      { year: "2006", event: "Drug war begins; cartels fracture and escalate violence" },
      { year: "2019", event: "AMLO takes power with anti-establishment platform" },
      { year: "2023", event: "Record drug violence; near-state capture in some regions" },
    ],
    conflicts: [
      { name: "Cartel Wars", status: "active", since: "2006" },
    ],
    allies: ["United States", "Canada", "EU"],
    rivals: [],
  },
  "Turkey": {
    name: "Turkey",
    capital: "Ankara",
    population: "85 million",
    region: "Middle East / Europe",
    riskLevel: 5,
    stabilityScore: 50,
    leader: { name: "Recep Tayyip Erdoğan", title: "President" },
    summary: "Strategically positioned NATO member that plays all sides — balancing US, Russia, Ukraine, and Middle Eastern powers for maximum leverage.",
    currentSituation: "Hosting Ukraine-Russia talks; blocking Swedish NATO bid until late 2023; military operations in northern Syria.",
    timeline: [
      { year: "1923", event: "Republic of Turkey founded by Atatürk from Ottoman remnants" },
      { year: "1952", event: "Joins NATO" },
      { year: "1974", event: "Invades Cyprus; Northern Cyprus occupied" },
      { year: "2016", event: "Failed coup attempt; Erdoğan consolidates power" },
      { year: "2023", event: "Devastating earthquakes kill 50,000; Erdoğan re-elected" },
    ],
    conflicts: [
      { name: "Syria Military Operations", status: "active", since: "2016" },
      { name: "Kurdish PKK Conflict", status: "active", since: "1984" },
    ],
    allies: ["NATO members", "Azerbaijan", "Qatar"],
    rivals: ["Greece", "Armenia", "Syria", "Kurdish forces"],
  },
  "Sudan": {
    name: "Sudan",
    capital: "Khartoum",
    population: "46 million",
    region: "North Africa",
    riskLevel: 10,
    stabilityScore: 12,
    leader: { name: "Abdel Fattah al-Burhan", title: "General / De Facto Leader" },
    summary: "Sudan is experiencing one of the world's worst humanitarian crises since April 2023, when war erupted between the military and the Rapid Support Forces.",
    currentSituation: "Civil war between SAF and RSF; over 8 million displaced; widespread atrocities reported in Darfur.",
    timeline: [
      { year: "1956", event: "Independence from Anglo-Egyptian rule" },
      { year: "1989", event: "Military coup; Omar al-Bashir takes power" },
      { year: "2003", event: "Darfur genocide begins; ICC warrants issued" },
      { year: "2011", event: "South Sudan secedes after referendum" },
      { year: "2019", event: "Protests topple Bashir; transitional council formed" },
      { year: "2023", event: "War erupts between SAF and RSF; massive humanitarian crisis" },
    ],
    conflicts: [
      { name: "SAF-RSF Civil War", status: "active", since: "2023" },
      { name: "Darfur Crisis", status: "active", since: "2003" },
    ],
    allies: ["Egypt", "UAE"],
    rivals: ["Ethiopia (historically)"],
  },
  "Ethiopia": {
    name: "Ethiopia",
    capital: "Addis Ababa",
    population: "120 million",
    region: "East Africa",
    riskLevel: 7,
    stabilityScore: 35,
    leader: { name: "Abiy Ahmed", title: "Prime Minister" },
    summary: "Nobel Peace Prize laureate turned war leader. Peace deal ends Tigray war after two years of catastrophic conflict, but instability remains.",
    currentSituation: "Post-Tigray war reconstruction; Amhara region conflict; economic pressure.",
    timeline: [
      { year: "1896", event: "Battle of Adwa; Ethiopia defeats Italian invasion; independence preserved" },
      { year: "1936", event: "Italian occupation; restored after WWII" },
      { year: "1974", event: "Emperor Haile Selassie overthrown; Derg communist junta rules" },
      { year: "1991", event: "EPRDF rebels overthrow Derg; federal system established" },
      { year: "2020", event: "Tigray War begins; Abiy Ahmed sends federal troops" },
      { year: "2022", event: "Pretoria peace agreement ends Tigray war" },
    ],
    conflicts: [
      { name: "Tigray War", status: "resolved", since: "2020" },
      { name: "Amhara Conflict", status: "active", since: "2023" },
    ],
    allies: ["Kenya", "Djibouti", "AU"],
    rivals: ["Eritrea (historically)", "TPLF"],
  },
  "Myanmar": {
    name: "Myanmar",
    capital: "Naypyidaw",
    population: "54 million",
    region: "Southeast Asia",
    riskLevel: 9,
    stabilityScore: 14,
    leader: { name: "Min Aung Hlaing", title: "Commander-in-Chief" },
    summary: "Myanmar descended into civil war following the 2021 military coup. Resistance forces have made significant territorial gains against the junta by late 2023.",
    currentSituation: "Operation 1027 by resistance forces captured major towns; junta losing control; humanitarian collapse.",
    timeline: [
      { year: "1948", event: "Independence from Britain" },
      { year: "1962", event: "Military coup; decades of junta rule begin" },
      { year: "1990", event: "NLD wins election; results annulled; Suu Kyi imprisoned" },
      { year: "2015", event: "NLD wins landslide election; democratic transition begins" },
      { year: "2021", event: "Military coup overthrows elected government" },
      { year: "2023", event: "Resistance forces launch major Operation 1027 counteroffensive" },
    ],
    conflicts: [
      { name: "Civil War (Post-Coup)", status: "active", since: "2021" },
      { name: "Rohingya Crisis", status: "active", since: "2017" },
    ],
    allies: ["China", "Russia", "Thailand"],
    rivals: ["Resistance groups", "Western nations"],
  },
  "Afghanistan": {
    name: "Afghanistan",
    capital: "Kabul",
    population: "40 million",
    region: "Central Asia",
    riskLevel: 9,
    stabilityScore: 10,
    leader: { name: "Hibatullah Akhundzada", title: "Supreme Leader (Taliban)" },
    summary: "Taliban controls all territory following 2021 US withdrawal. The country faces catastrophic humanitarian crisis, women's rights collapse, and ISIS-K terrorism.",
    currentSituation: "Full Taliban control; women banned from education and work; ISIS-K attacks; deepening famine.",
    timeline: [
      { year: "1978", event: "Communist coup; Soviet invasion follows in 1979" },
      { year: "1989", event: "Soviet forces withdraw; civil war erupts" },
      { year: "1996", event: "Taliban takes Kabul; harsh Islamic rule imposed" },
      { year: "2001", event: "US invasion following 9/11; Taliban toppled" },
      { year: "2021", event: "US withdrawal; Taliban retakes power in days" },
      { year: "2022", event: "Girls banned from secondary school; international aid collapses" },
    ],
    conflicts: [
      { name: "ISIS-K Terrorism", status: "active", since: "2015" },
      { name: "Taliban Governance Resistance", status: "active", since: "2021" },
    ],
    allies: ["Pakistan (historically)", "China (cautious engagement)"],
    rivals: ["United States", "India", "ISIS-K"],
  },
  "Syria": {
    name: "Syria",
    capital: "Damascus",
    population: "21 million",
    region: "Middle East",
    riskLevel: 8,
    stabilityScore: 16,
    leader: { name: "Bashar al-Assad", title: "President" },
    summary: "Syria's civil war has killed 500,000+ and displaced half the population. The Assad government, backed by Russia and Iran, controls most territory.",
    currentSituation: "Assad government controls most territory; ISIS remnants active in desert; humanitarian crisis ongoing.",
    timeline: [
      { year: "1970", event: "Hafez al-Assad seizes power in coup" },
      { year: "2000", event: "Bashar al-Assad succeeds father after his death" },
      { year: "2011", event: "Arab Spring protests; brutal crackdown begins civil war" },
      { year: "2013", event: "Chemical weapons attack in Ghouta; international outrage" },
      { year: "2017", event: "Assad government recaptures Aleppo with Russian support" },
      { year: "2023", event: "Arab League readmits Syria; chemical weapons use unpunished" },
    ],
    conflicts: [
      { name: "Civil War", status: "active", since: "2011" },
      { name: "ISIS Remnants", status: "active", since: "2014" },
    ],
    allies: ["Russia", "Iran", "Hezbollah"],
    rivals: ["United States", "Turkey", "Israel", "Rebel groups"],
  },
  "Yemen": {
    name: "Yemen",
    capital: "Sana'a (Houthi) / Aden (Government)",
    population: "33 million",
    region: "Middle East",
    riskLevel: 9,
    stabilityScore: 8,
    leader: { name: "Rashad al-Alimi", title: "Presidential Leadership Council Chair" },
    summary: "Yemen is experiencing one of the world's worst humanitarian disasters after a decade of civil war between the Houthi movement and Saudi-backed government forces.",
    currentSituation: "Fragile truce; Houthis attacking Red Sea shipping in solidarity with Gaza; 21 million need humanitarian aid.",
    timeline: [
      { year: "1990", event: "North and South Yemen unify" },
      { year: "2011", event: "Arab Spring uprising; President Saleh resigns" },
      { year: "2014", event: "Houthi forces take Sana'a" },
      { year: "2015", event: "Saudi Arabia leads military intervention" },
      { year: "2023", event: "Saudi-Houthi talks progress; ceasefire holding tenuously" },
    ],
    conflicts: [
      { name: "Yemen Civil War", status: "active", since: "2015" },
      { name: "Houthi Red Sea Attacks", status: "active", since: "2023" },
    ],
    allies: ["Iran (Houthis)", "Saudi Arabia (Government)", "UAE (Government)"],
    rivals: ["Saudi Arabia (for Houthis)", "Iran (for Government)"],
  },
  "Venezuela": {
    name: "Venezuela",
    capital: "Caracas",
    population: "28 million",
    region: "South America",
    riskLevel: 7,
    stabilityScore: 22,
    leader: { name: "Nicolás Maduro", title: "President" },
    summary: "Venezuela's political and economic collapse has triggered the largest refugee crisis in Latin American history, with 7 million having fled the country.",
    currentSituation: "Maduro consolidates power; opposition repressed; oil revenues recovering but political crisis continues.",
    timeline: [
      { year: "1998", event: "Hugo Chávez elected; socialist Bolivarian Revolution begins" },
      { year: "2013", event: "Chávez dies; Maduro takes power" },
      { year: "2015", event: "Oil price collapse; economic freefall begins" },
      { year: "2019", event: "Guaidó declares parallel presidency; US backs opposition" },
      { year: "2023", event: "Maduro consolidates power; Guaidó's movement collapses" },
    ],
    conflicts: [
      { name: "Maduro vs. Opposition", status: "active", since: "2013" },
    ],
    allies: ["Cuba", "Russia", "China", "Iran"],
    rivals: ["United States", "Colombia"],
  },
  "Colombia": {
    name: "Colombia",
    capital: "Bogotá",
    population: "51 million",
    region: "South America",
    riskLevel: 5,
    stabilityScore: 48,
    leader: { name: "Gustavo Petro", title: "President" },
    summary: "Colombia is pursuing 'Total Peace' with guerrilla groups while remaining the world's largest cocaine producer. Complex transition after FARC peace deal.",
    currentSituation: "Peace negotiations with ELN and FARC dissidents; cocaine production at record levels.",
    timeline: [
      { year: "1948", event: "Assassination of Gaitán sparks La Violencia civil war" },
      { year: "1960s", event: "FARC and ELN guerrilla groups form" },
      { year: "2016", event: "Historic peace deal with FARC signed" },
      { year: "2022", event: "Petro becomes first leftist president; Total Peace policy" },
    ],
    conflicts: [
      { name: "ELN Insurgency", status: "active", since: "1964" },
      { name: "FARC Dissidents", status: "active", since: "2016" },
    ],
    allies: ["United States", "EU", "Regional neighbors"],
    rivals: ["Venezuela"],
  },
  "Democratic Republic of Congo": {
    name: "Democratic Republic of Congo",
    capital: "Kinshasa",
    population: "100 million",
    region: "Central Africa",
    riskLevel: 8,
    stabilityScore: 18,
    leader: { name: "Félix Tshisekedi", title: "President" },
    summary: "DRC contains vast mineral wealth vital to global tech supply chains, but the eastern region has experienced decades of conflict involving dozens of armed groups.",
    currentSituation: "M23 rebels backed by Rwanda control territory in eastern DRC; massive displacement ongoing.",
    timeline: [
      { year: "1960", event: "Independence from Belgium; Patrice Lumumba assassinated" },
      { year: "1965", event: "Mobutu seizes power; renames country Zaire" },
      { year: "1994", event: "Rwandan genocide spills over; First Congo War begins" },
      { year: "1997", event: "Mobutu ousted; renamed DRC" },
      { year: "1998", event: "Second Congo War — deadliest since WWII" },
      { year: "2023", event: "M23 backed by Rwanda escalates eastern conflict" },
    ],
    conflicts: [
      { name: "Eastern DRC Conflict", status: "active", since: "1996" },
      { name: "M23 Rebellion", status: "active", since: "2022" },
    ],
    allies: ["Angola", "AU", "UN peacekeepers"],
    rivals: ["Rwanda", "Uganda"],
  },
  "Nigeria": {
    name: "Nigeria",
    capital: "Abuja",
    population: "218 million",
    region: "West Africa",
    riskLevel: 6,
    stabilityScore: 40,
    leader: { name: "Bola Tinubu", title: "President" },
    summary: "Africa's most populous nation and largest economy faces Boko Haram terrorism, separatist movements, and economic hardship from subsidy removal.",
    currentSituation: "Naira devaluation causing economic pain; Boko Haram active; ECOWAS standoff with Niger junta.",
    timeline: [
      { year: "1960", event: "Independence from Britain" },
      { year: "1967", event: "Biafra war; over 1 million die" },
      { year: "1999", event: "Return to civilian rule after military era" },
      { year: "2009", event: "Boko Haram insurgency begins in northeast" },
      { year: "2023", event: "Tinubu elected; removes fuel subsidies; economic shock" },
    ],
    conflicts: [
      { name: "Boko Haram Insurgency", status: "active", since: "2009" },
      { name: "Farmer-Herder Violence", status: "active", since: "2010s" },
    ],
    allies: ["United States", "UK", "AU", "ECOWAS"],
    rivals: ["Boko Haram", "Niger (after coup)"],
  },
  "South Africa": {
    name: "South Africa",
    capital: "Pretoria / Cape Town",
    population: "60 million",
    region: "Southern Africa",
    riskLevel: 4,
    stabilityScore: 55,
    leader: { name: "Cyril Ramaphosa", title: "President" },
    summary: "South Africa is the continent's most industrialized economy but struggles with 33% unemployment, high inequality, and persistent power outages.",
    currentSituation: "Record 'load-shedding' power cuts; economic stagnation; BRICS+ summit hosted in 2023.",
    timeline: [
      { year: "1948", event: "Apartheid system formally introduced" },
      { year: "1990", event: "Nelson Mandela released; negotiations begin" },
      { year: "1994", event: "First democratic election; Mandela becomes president" },
      { year: "2009", event: "Jacob Zuma era; widespread corruption" },
      { year: "2023", event: "Hosts expanded BRICS+ summit; energy crisis worsens" },
    ],
    conflicts: [],
    allies: ["AU", "BRICS", "UK", "EU"],
    rivals: [],
  },
  "Egypt": {
    name: "Egypt",
    capital: "Cairo",
    population: "104 million",
    region: "North Africa",
    riskLevel: 5,
    stabilityScore: 46,
    leader: { name: "Abdel Fattah el-Sisi", title: "President" },
    summary: "Egypt controls the Suez Canal and serves as a key US partner in Middle East stability. Facing severe economic pressure and hosting millions of Sudanese refugees.",
    currentSituation: "Economic crisis; IMF negotiations; mediating Gaza ceasefire; Sudanese refugee influx.",
    timeline: [
      { year: "1952", event: "Revolution ends monarchy; republic established" },
      { year: "1979", event: "Peace treaty with Israel signed" },
      { year: "2011", event: "Arab Spring; Mubarak ousted" },
      { year: "2013", event: "Military coup removes elected President Morsi" },
      { year: "2023", event: "Economic crisis; pound devalues significantly" },
    ],
    conflicts: [
      { name: "Sinai Insurgency", status: "active", since: "2011" },
    ],
    allies: ["United States", "Saudi Arabia", "UAE", "Israel (covertly)"],
    rivals: ["Qatar (historically)", "Turkey (historically)"],
  },
  "Poland": {
    name: "Poland",
    capital: "Warsaw",
    population: "38 million",
    region: "Eastern Europe",
    riskLevel: 3,
    stabilityScore: 68,
    leader: { name: "Andrzej Duda", title: "President" },
    summary: "Poland is NATO's eastern bulwark, hosting US troops and providing the most arms to Ukraine by GDP percentage of any nation.",
    currentSituation: "Largest arms supplier to Ukraine; hosting 1 million+ Ukrainian refugees; major NATO buildup.",
    timeline: [
      { year: "1939", event: "Nazi Germany and USSR invade; WWII begins" },
      { year: "1945", event: "Liberation; comes under Soviet sphere" },
      { year: "1980", event: "Solidarity trade union challenges communist rule" },
      { year: "1989", event: "First free elections in Eastern Bloc; peaceful transition" },
      { year: "2004", event: "Joins EU and NATO" },
      { year: "2022", event: "Becomes critical military corridor for Ukraine support" },
    ],
    conflicts: [],
    allies: ["United States", "NATO", "EU", "Ukraine"],
    rivals: ["Russia", "Belarus"],
  },
  "Indonesia": {
    name: "Indonesia",
    capital: "Jakarta",
    population: "275 million",
    region: "Southeast Asia",
    riskLevel: 3,
    stabilityScore: 60,
    leader: { name: "Joko Widodo", title: "President" },
    summary: "World's largest archipelago nation and fourth most populous country. A major emerging economy bridging Southeast Asian politics as ASEAN's largest member.",
    currentSituation: "Capital moving to new Nusantara city; ASEAN chair; balancing US and China relations.",
    timeline: [
      { year: "1945", event: "Independence declared; Dutch colonial war follows" },
      { year: "1965", event: "Anti-communist purge; Suharto takes power" },
      { year: "1998", event: "Asian financial crisis topples Suharto; democratization begins" },
      { year: "2004", event: "First direct presidential election" },
      { year: "2023", event: "ASEAN chair; Prabowo elected as next president" },
    ],
    conflicts: [
      { name: "Papua Insurgency", status: "active", since: "1960s" },
    ],
    allies: ["ASEAN", "United States", "Australia", "China"],
    rivals: [],
  },
  "Australia": {
    name: "Australia",
    capital: "Canberra",
    population: "26 million",
    region: "Oceania",
    riskLevel: 1,
    stabilityScore: 84,
    leader: { name: "Anthony Albanese", title: "Prime Minister" },
    summary: "Stable liberal democracy and key US ally in the Indo-Pacific. AUKUS submarine partnership aims to counter Chinese influence in the Pacific.",
    currentSituation: "AUKUS nuclear submarine deal; China relations slowly improving after trade war.",
    timeline: [
      { year: "1901", event: "Federation of Australia formed" },
      { year: "1967", event: "Aboriginal Australians counted in census; rights begin" },
      { year: "2000", event: "Sydney Olympics" },
      { year: "2020", event: "Devastating bushfire season; COVID response" },
      { year: "2021", event: "AUKUS submarine pact announced; China relations deteriorate" },
    ],
    conflicts: [],
    allies: ["United States", "United Kingdom", "New Zealand", "Japan"],
    rivals: ["China"],
  },
  "Canada": {
    name: "Canada",
    capital: "Ottawa",
    population: "38 million",
    region: "North America",
    riskLevel: 1,
    stabilityScore: 85,
    leader: { name: "Justin Trudeau", title: "Prime Minister" },
    summary: "G7 member and close US ally with vast natural resources. Faces domestic debates over housing, indigenous rights, and defence spending commitments to NATO.",
    currentSituation: "Housing affordability crisis; NATO defence spending debates; strong Ukraine support.",
    timeline: [
      { year: "1867", event: "Confederation; Dominion of Canada formed" },
      { year: "1982", event: "Full constitutional independence from UK" },
      { year: "1995", event: "Quebec sovereignty referendum narrowly defeated" },
      { year: "2015", event: "Trudeau elected; progressive agenda" },
      { year: "2022", event: "Freedom Convoy truckers protest; Emergencies Act invoked" },
    ],
    conflicts: [],
    allies: ["United States", "United Kingdom", "France", "NATO"],
    rivals: [],
  },
  "Argentina": {
    name: "Argentina",
    capital: "Buenos Aires",
    population: "46 million",
    region: "South America",
    riskLevel: 5,
    stabilityScore: 40,
    leader: { name: "Javier Milei", title: "President" },
    summary: "Argentina elected libertarian economist Milei promising radical shock therapy for its chronic inflation crisis exceeding 140% annually.",
    currentSituation: "Hyperinflation; Milei implementing extreme austerity; peso devaluation; IMF debt restructuring.",
    timeline: [
      { year: "1976", event: "Military coup; Dirty War — 30,000 disappeared" },
      { year: "1983", event: "Return to democracy after Falklands War defeat" },
      { year: "2001", event: "Economic collapse; 'que se vayan todos' protests" },
      { year: "2023", event: "Milei wins election; radical economic shock therapy begins" },
    ],
    conflicts: [],
    allies: ["Brazil", "Chile", "IMF (creditor)"],
    rivals: ["United Kingdom (Falklands)"],
  },
  "Greece": {
    name: "Greece",
    capital: "Athens",
    population: "10.7 million",
    region: "Southern Europe",
    riskLevel: 3,
    stabilityScore: 62,
    leader: { name: "Kyriakos Mitsotakis", title: "Prime Minister" },
    summary: "Eurozone member rebuilding after a decade-long debt crisis. Ongoing tensions with Turkey over maritime boundaries and migration.",
    currentSituation: "Recovering economy; Turkey tensions over Aegean; migration pressure at EU border.",
    timeline: [
      { year: "1821", event: "Greek War of Independence from Ottoman Empire" },
      { year: "1967", event: "Military coup; Colonels' junta rules until 1974" },
      { year: "1981", event: "Joins EU (then EEC)" },
      { year: "2010", event: "Sovereign debt crisis; EU/IMF bailouts begin" },
      { year: "2018", event: "Prespa Agreement resolves name dispute with North Macedonia" },
    ],
    conflicts: [],
    allies: ["EU", "NATO", "United States"],
    rivals: ["Turkey"],
  },
  "Spain": {
    name: "Spain",
    capital: "Madrid",
    population: "47 million",
    region: "Southern Europe",
    riskLevel: 2,
    stabilityScore: 70,
    leader: { name: "Pedro Sánchez", title: "Prime Minister" },
    summary: "Major EU economy navigating political fragmentation and the Catalan independence movement while managing significant migration pressures.",
    currentSituation: "Catalan amnesty law controversy; coalition government fragility; Canary Islands migration.",
    timeline: [
      { year: "1936", event: "Civil war; Franco wins; 40 years of dictatorship" },
      { year: "1975", event: "Franco dies; democratic transition" },
      { year: "1986", event: "Joins EU and NATO" },
      { year: "2017", event: "Catalan independence referendum; direct rule imposed" },
      { year: "2023", event: "Sánchez coalition includes Catalan independence parties" },
    ],
    conflicts: [
      { name: "Catalan Independence", status: "frozen", since: "2017" },
    ],
    allies: ["EU", "NATO", "United States"],
    rivals: [],
  },
  "Italy": {
    name: "Italy",
    capital: "Rome",
    population: "60 million",
    region: "Southern Europe",
    riskLevel: 2,
    stabilityScore: 68,
    leader: { name: "Giorgia Meloni", title: "Prime Minister" },
    summary: "Italy's first far-right government since WWII is pursuing stricter migration policies while remaining a committed EU and NATO member.",
    currentSituation: "Migration management pressure; Italy-EU tensions over deficit rules; Ukraine support continued.",
    timeline: [
      { year: "1861", event: "Italian unification" },
      { year: "1943", event: "Mussolini falls; Italy switches sides in WWII" },
      { year: "1946", event: "Republic declared" },
      { year: "1957", event: "Founding member of European Economic Community" },
      { year: "2022", event: "Meloni elected; first far-right government since WWII" },
    ],
    conflicts: [],
    allies: ["EU", "NATO", "United States"],
    rivals: [],
  },
  "Belarus": {
    name: "Belarus",
    capital: "Minsk",
    population: "9.4 million",
    region: "Eastern Europe",
    riskLevel: 7,
    stabilityScore: 25,
    leader: { name: "Alexander Lukashenko", title: "President" },
    summary: "The last dictatorship in Europe, Belarus hosts Russian nuclear weapons and serves as a staging ground for the Ukraine war.",
    currentSituation: "Russian nuclear weapons stationed; Wagner Group relocated here briefly; opposition in exile.",
    timeline: [
      { year: "1991", event: "Independence from Soviet Union" },
      { year: "1994", event: "Lukashenko elected; consolidates authoritarian rule" },
      { year: "2020", event: "Fraudulent election triggers massive protests; brutal crackdown" },
      { year: "2021", event: "Forced landing of Ryanair to arrest journalist Protasevich" },
      { year: "2023", event: "Russian tactical nukes deployed to Belarus" },
    ],
    conflicts: [],
    allies: ["Russia"],
    rivals: ["EU", "NATO", "United States", "Ukraine"],
  },
  "Sweden": {
    name: "Sweden",
    capital: "Stockholm",
    population: "10.5 million",
    region: "Northern Europe",
    riskLevel: 1,
    stabilityScore: 88,
    leader: { name: "Ulf Kristersson", title: "Prime Minister" },
    summary: "Sweden ended 200 years of neutrality by joining NATO in March 2024 following Russia's invasion of Ukraine.",
    currentSituation: "Newly joined NATO; gang violence domestic concern; significant Ukraine military aid.",
    timeline: [
      { year: "1814", event: "Begins 200 years of neutrality policy" },
      { year: "1946", event: "Joins United Nations" },
      { year: "1995", event: "Joins European Union" },
      { year: "2022", event: "Applies for NATO membership after Ukraine invasion" },
      { year: "2024", event: "Officially joins NATO after Turkey, Hungary approve" },
    ],
    conflicts: [],
    allies: ["NATO", "EU", "United States", "Finland"],
    rivals: ["Russia"],
  },
  "Finland": {
    name: "Finland",
    capital: "Helsinki",
    population: "5.6 million",
    region: "Northern Europe",
    riskLevel: 1,
    stabilityScore: 90,
    leader: { name: "Alexander Stubb", title: "President" },
    summary: "Finland joined NATO in April 2023, doubling NATO's border with Russia. It has the highest military readiness in Northern Europe.",
    currentSituation: "New NATO member; 1300km Russia border; highest military participation rate in Europe.",
    timeline: [
      { year: "1917", event: "Independence from Russia declared" },
      { year: "1939", event: "Winter War against Soviet Union; Finland holds out" },
      { year: "1948", event: "Finlandization policy balancing Soviet relations" },
      { year: "1995", event: "Joins European Union" },
      { year: "2023", event: "Joins NATO; ends decades of military non-alignment" },
    ],
    conflicts: [],
    allies: ["NATO", "EU", "Sweden", "United States"],
    rivals: ["Russia"],
  },
  "Philippines": {
    name: "Philippines",
    capital: "Manila",
    population: "113 million",
    region: "Southeast Asia",
    riskLevel: 5,
    stabilityScore: 52,
    leader: { name: "Ferdinand Marcos Jr.", title: "President" },
    summary: "Southeast Asian democracy facing increasing Chinese aggression in the South China Sea while pivoting back toward its US alliance.",
    currentSituation: "South China Sea standoffs with China at Second Thomas Shoal; expanded US base access granted.",
    timeline: [
      { year: "1898", event: "Independence from Spain; US occupation follows" },
      { year: "1946", event: "Independence from United States" },
      { year: "1972", event: "Marcos Sr. declares martial law; dictatorship begins" },
      { year: "1986", event: "People Power Revolution; Marcos ousted" },
      { year: "2022", event: "Marcos Jr. wins election; pivots toward US alliance" },
    ],
    conflicts: [
      { name: "South China Sea Disputes", status: "active", since: "2009" },
      { name: "Mindanao Insurgency", status: "frozen", since: "1970s" },
    ],
    allies: ["United States", "Japan", "Australia"],
    rivals: ["China"],
  },
  "Taiwan": {
    name: "Taiwan",
    capital: "Taipei",
    population: "23 million",
    region: "East Asia",
    riskLevel: 8,
    stabilityScore: 72,
    leader: { name: "Lai Ching-te", title: "President" },
    summary: "Taiwan is a thriving democracy and semiconductor powerhouse facing existential threat from China, which claims it as its territory.",
    currentSituation: "Increased Chinese military encirclement drills; election of pro-independence president Lai; US arms deliveries.",
    timeline: [
      { year: "1895", event: "Japan colonizes Taiwan after First Sino-Japanese War" },
      { year: "1949", event: "KMT government retreats to Taiwan after civil war" },
      { year: "1971", event: "PRC replaces Taiwan at United Nations" },
      { year: "1987", event: "Martial law ends; democratization begins" },
      { year: "2024", event: "Lai Ching-te elected; China conducts large military exercises" },
    ],
    conflicts: [
      { name: "Cross-Strait Tensions", status: "active", since: "1949" },
    ],
    allies: ["United States (unofficial)", "Japan", "Australia"],
    rivals: ["China"],
  },
};

export function getCountryData(name: string): CountryRecord | undefined {
  const exact = COUNTRY_DATABASE[name];
  if (exact) return exact;

  const lower = name.toLowerCase().trim();
  for (const [key, val] of Object.entries(COUNTRY_DATABASE)) {
    if (key.toLowerCase() === lower) return val;
    if (key.toLowerCase().includes(lower) || lower.includes(key.toLowerCase())) {
      return val;
    }
  }
  return undefined;
}

export function computeGlobalRiskSeconds(): number {
  const entries = Object.values(COUNTRY_DATABASE);
  const sorted = [...entries].sort((a, b) => b.riskLevel - a.riskLevel);
  const top10 = sorted.slice(0, 10);
  const avgRisk = top10.reduce((sum, c) => sum + c.riskLevel, 0) / top10.length;
  const normalized = avgRisk / 10;
  const seconds = Math.round(DOOMSDAY_BASE_SECONDS + (1 - normalized) * 150);
  return Math.max(15, Math.min(seconds, 300));
}

export function computeRiskForCountry(country: CountryRecord): number {
  return country.riskLevel / 10;
}

export const RISK_LABELS: Record<number, string> = {
  1: "Stable",
  2: "Low Risk",
  3: "Moderate",
  4: "Elevated",
  5: "Significant",
  6: "High",
  7: "Very High",
  8: "Critical",
  9: "Severe",
  10: "Extreme",
};

export const RISK_COLORS: Record<number, string> = {
  1: "#22c55e",
  2: "#84cc16",
  3: "#a3e635",
  4: "#facc15",
  5: "#fb923c",
  6: "#f97316",
  7: "#ef4444",
  8: "#dc2626",
  9: "#b91c1c",
  10: "#7f1d1d",
};
