/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SituationRoomRouteImport } from './routes/situation-room'
import { Route as PresidentialSimRouteImport } from './routes/presidential-sim'
import { Route as NewsShieldRouteImport } from './routes/news-shield'
import { Route as ConflictMapRouteImport } from './routes/conflict-map'
import { Route as IndexRouteImport } from './routes/index'

const SituationRoomRoute = SituationRoomRouteImport.update({
  id: '/situation-room',
  path: '/situation-room',
  getParentRoute: () => rootRouteImport,
} as any)
const PresidentialSimRoute = PresidentialSimRouteImport.update({
  id: '/presidential-sim',
  path: '/presidential-sim',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsShieldRoute = NewsShieldRouteImport.update({
  id: '/news-shield',
  path: '/news-shield',
  getParentRoute: () => rootRouteImport,
} as any)
const ConflictMapRoute = ConflictMapRouteImport.update({
  id: '/conflict-map',
  path: '/conflict-map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conflict-map': typeof ConflictMapRoute
  '/news-shield': typeof NewsShieldRoute
  '/presidential-sim': typeof PresidentialSimRoute
  '/situation-room': typeof SituationRoomRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conflict-map': typeof ConflictMapRoute
  '/news-shield': typeof NewsShieldRoute
  '/presidential-sim': typeof PresidentialSimRoute
  '/situation-room': typeof SituationRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conflict-map': typeof ConflictMapRoute
  '/news-shield': typeof NewsShieldRoute
  '/presidential-sim': typeof PresidentialSimRoute
  '/situation-room': typeof SituationRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conflict-map'
    | '/news-shield'
    | '/presidential-sim'
    | '/situation-room'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conflict-map'
    | '/news-shield'
    | '/presidential-sim'
    | '/situation-room'
  id:
    | '__root__'
    | '/'
    | '/conflict-map'
    | '/news-shield'
    | '/presidential-sim'
    | '/situation-room'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConflictMapRoute: typeof ConflictMapRoute
  NewsShieldRoute: typeof NewsShieldRoute
  PresidentialSimRoute: typeof PresidentialSimRoute
  SituationRoomRoute: typeof SituationRoomRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/situation-room': {
      id: '/situation-room'
      path: '/situation-room'
      fullPath: '/situation-room'
      preLoaderRoute: typeof SituationRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presidential-sim': {
      id: '/presidential-sim'
      path: '/presidential-sim'
      fullPath: '/presidential-sim'
      preLoaderRoute: typeof PresidentialSimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news-shield': {
      id: '/news-shield'
      path: '/news-shield'
      fullPath: '/news-shield'
      preLoaderRoute: typeof NewsShieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conflict-map': {
      id: '/conflict-map'
      path: '/conflict-map'
      fullPath: '/conflict-map'
      preLoaderRoute: typeof ConflictMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConflictMapRoute: ConflictMapRoute,
  NewsShieldRoute: NewsShieldRoute,
  PresidentialSimRoute: PresidentialSimRoute,
  SituationRoomRoute: SituationRoomRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
